name: Docker Slim

#Only trigger, when the build workflow succeeded
on:
<<<<<<< HEAD
  push:
    branches:
      - master
      - main
    paths:
      - ".github/workflows/docker-slim.yml"
=======
>>>>>>> 0deb0635 (new website)
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

<<<<<<< HEAD
# on:
#   push:
#     branches:
#       - 'master'

jobs:
  build:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-based-on-the-conclusion-of-another-workflow
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.repository_owner == 'alshedivat' }}
    runs-on: ubuntu-latest
=======
# on: 
#   push:
#     branches: 
#       - 'master'

jobs: 
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'alshedivat'

>>>>>>> 0deb0635 (new website)
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
<<<<<<< HEAD
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: update docker-compose
        shell: bash
        run: |
          sed -i "s|\.:|${{ github.workspace }}:|g" ${{ github.workspace }}/docker-compose.yml
          cat ${{ github.workspace }}/docker-compose.yml

      - uses: kitabisa/docker-slim-action@v1.1.1
        env:
          DSLIM_PULL: true
          DSLIM_COMPOSE_FILE: ${{ github.workspace }}/docker-compose.yml
          DSLIM_TARGET_COMPOSE_SVC: jekyll
          DSLIM_CONTINUE_AFTER: signal
        with:
          target: amirpourmand/al-folio
          tag: "slim"

      # Push to the registry
      - run: docker image push amirpourmand/al-folio:slim
=======
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: update docker-compose
      shell: bash
      run:  |
        sed -i "s|\.:|${{ github.workspace }}:|g" ${{ github.workspace }}/docker-compose.yml 
        cat ${{ github.workspace }}/docker-compose.yml 
        
    - uses: kitabisa/docker-slim-action@v1.0.3
      env:
        DSLIM_PULL: true
        DSLIM_COMPOSE_FILE: ${{ github.workspace }}/docker-compose.yml
        DSLIM_TARGET_COMPOSE_SVC: jekyll
        DSLIM_CONTINUE_AFTER: signal
      with:
        target: amirpourmand/al-folio
        tag: "slim"

    # Push to the registry
    - run: docker image push amirpourmand/al-folio:slim
>>>>>>> 0deb0635 (new website)
